version: '3.4'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/mozart/
    command: /bin/sh -c "while sleep 1000; do :; done"
