name: Lint, analyse and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        run: docker compose run --rm builder composer install
      - name: Run linting
        run: docker compose run --rm builder composer test:lint
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        run: docker compose run --rm builder composer install
      - name: Run testing
        run: docker compose run --rm builder composer test:phpunit
  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        run: docker compose run --rm builder composer install
      - name: Run analysis
        run: docker compose run --rm builder composer test:phpstan
