name: Lint, test and analyse

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  linting:
    needs: docker_build
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v4
      - name: Run linting
        run: docker compose run --rm actions-tester composer test:lint
  testing:
    needs: docker_build
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v4
      - name: Run testing
        run: docker compose run --rm actions-tester composer test:phpunit
  analysis:
    needs: docker_build
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - uses: actions/checkout@v4
      - name: Run analysis
        run: docker compose run --rm actions-tester composer test:phpstan
